# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: prepare-pull-request

env:
  NODE_VERSION: 14.x

on:
  pull_request:
    branches: [master, main]

jobs:
  install-and-prettify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: npm install
      - uses: stefanzweifel/git-auto-commit-action@v4.7.2
        with:
          commit_message: installing
          branch: ${{ github.head_ref }}

      - run: npm run prettify
      - uses: stefanzweifel/git-auto-commit-action@v4.7.2
        with:
          commit_message: ":nail_care: prettify"
          branch: ${{ github.head_ref }}
